In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error,mean_absolute_error,r2_score
ds=pd.read_csv('/content/drive/MyDrive/salary_dataset.csv')

In [ ]:
ds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Unnamed: 0       30 non-null     int64
 1   YearsExperience  30 non-null     float64
 2   Salary           30 non-null     float64
dtypes: float64(2), int64(1)
memory usage: 852.0 bytes

In [ ]:
ds.describe()

       Unnamed: 0  YearsExperience         Salary
count   30.000000        30.000000      30.000000
mean    14.500000         5.413333   76004.000000
std      8.803408         2.837888   27414.429785
min      0.000000         1.200000   37732.000000
25%      7.250000         3.300000   56721.750000
50%     14.500000         4.800000   65238.000000
75%     21.750000         7.800000  100545.750000
max     29.000000        10.600000  122392.000000

In [ ]:
ds.isnull().sum()

Unnamed: 0         0
YearsExperience    0
Salary             0
dtype: int64

In [ ]:
ds.head()

   Unnamed: 0  YearsExperience   Salary
0           0              1.2  39344.0
1           1              1.4  46206.0
2           2              1.6  37732.0
3           3              2.1  43526.0
4           4              2.3  39892.0

In [ ]:
x=ds.drop(['Salary','Unnamed: 0'],axis=1)
Y=ds["Salary"]

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, Y, test_size=0.3, random_state=42)

In [ ]:
model = LinearRegression()
model=model.fit(x_train,y_train)

In [ ]:
predictSalary=model.predict(x_test)

In [ ]:
predictSalary

array([115574.62288352,  71680.93878159, 102499.90847018,  75416.57147111,
        55804.4998511 ,  60474.04071301, 122111.98009019, 107169.44933209,
        63275.76523015])

In [ ]:
errors=mean_squared_error(y_test,predictSalary)
print("Mean_absolute error:",errors)
r2=r2_score(y_test,predictSalary)
print("R2 score:",r2)

errors=mean_absolute_error(y_test,predictSalary)
print("Mean_absolute error:",errors)

mean_absolute_error= 0.07744778459829141

Mean_absolute error: 37784662.46621308
R2 score: 0.9414466227178215
Mean_absolute error: 5161.328710400178

In [4]:
import matplotlib.pyplot as plt
plt.scatter(x,Y, color="blue")
plt.plot(x,model.predict(x), color="red")

NameError: name 'x' is not defined